server:
  name: main
  #host: localhost
  port: 8080
cache:
  enable: false
  interval: 3600
  adapter: file #memory,redis,memcache
  #path: data/caches #addr=127.0.0.1:6379,password=macaron
logger:
  enable: true
  #isJson: true
  #fileSize: 5
  #fileCount: 5
token:
  enable: true
  httponly: false
  name: ks
  key:  LQ6A4Y1R3KOB9D4JX593MGW44QMJ1LNC
  path: /
  #domain:
datasorce:
  main:
    enable: true
    driver: mysql
    url: root:root@tcp(localhost:3306)/test?charset=utf8
  mongo:
    enable: true
    driver: mongo
    url: mongodb://root:123456@localhost