server:
  name: main
  #host: localhost
  port: 8081
web:
  gzip: true
  template: renderer #pongo2,renderer
cache:
  enable: false
  interval: 3600
  adapter: file #memory,redis,memcache
  configs: data/caches #addr=127.0.0.1:6379,password=macaron
logger:
  enable: true
  path: run.log
  prefix: ruis-
token:
  enable: true
  httponly: false
  name: ks
  key:  LQ6A4Y1R3KOB9D4JX593MGW44QMJ1LNC
  path: /
  #domain:
db:
  enable: true
  driver: mysql
  url: root:root@tcp(localhost:3306)/test?charset=utf8
consul:
  enable: false
  #host: localhost
  #port: 8500
  id: go-cloud-main
  name: go-cloud
  reghost: localhost
  #tags: [123,345,654]
mongo:
  enable: false
  url: mongodb://root:123456@localhost/test